export default [
  {
    locationName: "Cowboy Donuts of Spanish Fork",
    contactFirst: "Derek",
    contactLast: "Johnson",
    contactPhone: "(307) 871-0569",
    contactEmail: "derekjohnson307@gmail.com",
    locationAddress: "1306 E Center St",
    locationCity: "Spanish Fork",
    locationState: "Utah",
    locationZip: "84660",
    "": ""
  },
  {
    locationName: "Four Foods Group",
    contactFirst: "Steve",
    contactLast: "Lecheminant",
    contactPhone: "(385) 368-6750",
    contactEmail: "slecheminant@fourfoodsgroup.com",
    locationAddress: "871 S Auto Mall Drive",
    locationCity: "American Fork",
    locationState: "UT",
    locationZip: "84003",
    "": ""
  },

  {
    locationName: "Kneaders of Ahwatukee ",
    contactFirst: "Josh",
    contactLast: "Tycksen",
    contactPhone: "(801) 671-7110",
    contactEmail: "josh@kneaders.com",
    locationAddress: "4730 E Ray Road",
    locationCity: "Ahwatukee",
    locationState: "Arizona",
    locationZip: "85044",
    "": ""
  },
  {
    locationName: "Kneaders of Arvada",
    contactFirst: "Shana",
    contactLast: "Owens",
    contactPhone: "(720) 287-5369",
    contactEmail: "arvada@kneaders.com",
    locationAddress: "7945 N Wadsworth Blvd",
    locationCity: "Arvada",
    locationState: "Colorado",
    locationZip: "80003",
    "": ""
  },
  {
    locationName: "Kneaders of Aurora",
    contactFirst: "Kip ",
    contactLast: "Lewis",
    contactPhone: "(720) 984-1875",
    contactEmail: "kip@kneaders.com",
    locationAddress: "14455 E Arapahoe Rd",
    locationCity: "Aurora",
    locationState: "Colorado",
    locationZip: "80016",
    "": ""
  },
  {
    locationName: "Kneaders of Avondale",
    contactFirst: "Joe",
    contactLast: "Gallegos",
    contactPhone: "(480) 323-9251",
    contactEmail: "gallegosjoee1108@gmail.com",
    locationAddress: "10112 W McDowell Rd",
    locationCity: "Avondale",
    locationState: "Arizona",
    locationZip: "85323",
    "": ""
  },
  {
    locationName: "Kneaders of Belton",
    contactFirst: "Jonathan",
    contactLast: "Day",
    contactPhone: "(801) 916-6035",
    contactEmail: "belton@kneaders.com",
    locationAddress: "621 E Markey Pkwy",
    locationCity: "Belton",
    locationState: "MO",
    locationZip: "64012",
    "": ""
  },
  {
    locationName: "Kneaders of Blue Springs",
    contactFirst: "Michelle",
    contactLast: "Spilman",
    contactPhone: "(602) 330-2930",
    contactEmail: "michelle@kneaders.com",
    locationAddress: "800 NE Coronado Drive",
    locationCity: "Blue Springs",
    locationState: "MO",
    locationZip: "64014",
    "": ""
  },
  {
    locationName: "Kneaders of Bountiful",
    contactFirst: "Stockton",
    contactLast: "Nye",
    contactPhone: "(801) 928-4945",
    contactEmail: "mark@kneaders.com",
    locationAddress: "1050 North 500 East",
    locationCity: "Bountiful",
    locationState: "Utah",
    locationZip: "84054",
    "": ""
  },
  {
    locationName: "Kneaders of Castle Rock",
    contactFirst: "Cody",
    contactLast: "Wilson",
    contactPhone: "(208) 604-1414",
    contactEmail: "cody@kneaders.com",
    locationAddress: "826 New Memphis CT",
    locationCity: "Castle Rock",
    locationState: "Colorado",
    locationZip: "80109",
    "": ""
  },
  {
    locationName: "Kneaders of Chandler",
    contactFirst: "Kellen",
    contactLast: "Sears",
    contactPhone: "(480) 776-7822",
    contactEmail: "kellen@kneaders.com",
    locationAddress: "1090 W Queen Creek Rd",
    locationCity: "Chandler",
    locationState: "Arizona",
    locationZip: "85248",
    "": ""
  },
  {
    locationName: "Kneaders of City Creek",
    contactFirst: "Holly",
    contactLast: "Watson",
    contactPhone: "(801) 547-7005",
    contactEmail: "holly@kneaders.com",
    locationAddress: "28 South State Street",
    locationCity: "Salt Lake City",
    locationState: "Utah",
    locationZip: "84111",
    "": ""
  },
  {
    locationName: "Kneaders of Colorado Springs",
    contactFirst: "Tony",
    contactLast: "Jenkins",
    contactPhone: "(801) 824-2318",
    contactEmail: "tony@kneaders.com",
    locationAddress: "3430 Cinema Point",
    locationCity: "Colorado Springs",
    locationState: "Colorado",
    locationZip: "80922",
    "": ""
  },
  {
    locationName: "Kneaders of Craig Rd",
    contactFirst: "Amy",
    contactLast: "Nash",
    contactPhone: "(315) 395-7375",
    contactEmail: "anash@kneaders.com",
    locationAddress: "7100 W Craig Rd",
    locationCity: "Las Vegas",
    locationState: "Nevada",
    locationZip: "89129",
    "": ""
  },
  {
    locationName: "Kneaders of Draper",
    contactFirst: "Derrick",
    contactLast: "Deaton",
    contactPhone: "(801) 580-8238",
    contactEmail: "derrick@kneaders.com",
    locationAddress: "177 East 13800 South",
    locationCity: "Draper",
    locationState: "Utah",
    locationZip: "84020"
  },
  {
    locationName: "Kneaders of Fort Union",
    contactFirst: "Rick",
    contactLast: "Sheppard",
    contactPhone: "(801) 563-1991",
    contactEmail: "rick@kneaders.com",
    locationAddress: "742 Fort Union Blvd",
    locationCity: "Midvale",
    locationState: "Utah",
    locationZip: "84047"
  },
  {
    locationName: "Kneaders of Gilbert Baseline",
    contactFirst: "Ben",
    contactLast: "Toa",
    contactPhone: "(801) 634-5988",
    contactEmail: "ben@kneaders.com",
    locationAddress: "5155 East Baseline Road",
    locationCity: "Gilbert",
    locationState: "Arizona",
    locationZip: "85234"
  },
  {
    locationName: "Kneaders of Gilbert Santan",
    contactFirst: "Grant",
    contactLast: "Mcnabb",
    contactPhone: "(480) 290-1485",
    contactEmail: "daniel@kneaders.com",
    locationAddress: "2910 South Santan Village Parkway",
    locationCity: "Gilbert",
    locationState: "Arizona",
    locationZip: "85296"
  },
  {
    locationName: "Kneaders of Glendale",
    contactFirst: "Matt",
    contactLast: "Condie",
    contactPhone: "(435) 773-5877",
    contactEmail: "mcondie@kneaders.com",
    locationAddress: "20630 N 75th Ave",
    locationCity: "Glendale",
    locationState: "Arizona",
    locationZip: "85308"
  },
  {
    locationName: "Kneaders of Heber",
    contactFirst: "Jason",
    contactLast: "Giles",
    contactPhone: "801-709-3758",
    contactEmail: "jason@kneaders.com",
    locationAddress: "1020 South Main Street",
    locationCity: "Heber",
    locationState: "Utah",
    locationZip: "84032"
  },
  {
    locationName: "Kneaders of Henderson",
    contactFirst: "Riley",
    contactLast: "",
    contactPhone: "(801) 888-2010",
    contactEmail: "jpeterson@kneaders.com",
    locationAddress: " 11271 S Eastern Ave",
    locationCity: "Henderson",
    locationState: "Nevada",
    locationZip: "89052"
  },
  {
    locationName: "Kneaders of Highlands Ranch",
    contactFirst: "Joe",
    contactLast: "Barnett",
    contactPhone: "(303) 981-0747",
    contactEmail: "jbarnett@kneaders.com",
    locationAddress: "1105 Sergeant Jon Stiles Dr",
    locationCity: "Highlands Ranch",
    locationState: "Colorado",
    locationZip: "80129"
  },
  {
    locationName: "Kneaders of Indian School",
    contactFirst: "Kate",
    contactLast: "Keenan",
    contactPhone: "(801) 695-3010",
    contactEmail: "kate@kneaders.com",
    locationAddress: "4126 E Indian School Rd",
    locationCity: "Phoenix",
    locationState: "Arizona",
    locationZip: "85018"
  },
  {
    locationName: "Kneaders of Jordan Landing",
    contactFirst: "Danny",
    contactLast: "Deaton",
    contactPhone: "(801) 637-9613",
    contactEmail: "danny@kneaders.com",
    locationAddress: "7713 South Jordan Landing Blvd",
    locationCity: "West Jordan",
    locationState: "Utah",
    locationZip: "84084"
  },
  {
    locationName: "Kneaders of Kaysville",
    contactFirst: "Brett",
    contactLast: "Rassmussen",
    contactPhone: "(801) 786-9362",
    contactEmail: "brett@kneaders.com",
    locationAddress: "1324 West 200 North",
    locationCity: "Kaysville",
    locationState: "Utah",
    locationZip: "84037"
  },
  {
    locationName: "Kneaders of Layton",
    contactFirst: "Kensy",
    contactLast: "Moser",
    contactPhone: "(801) 928-1743",
    contactEmail: "layton@kneaders.com",
    locationAddress: "480 West Antelope Drive",
    locationCity: "Layton",
    locationState: "Utah",
    locationZip: "84041"
  },
  {
    locationName: "Kneaders of Lehi",
    contactFirst: "Chad",
    contactLast: "Newman",
    contactPhone: "",
    contactEmail: "cnewman@fourfoodsgroup.com",
    locationAddress: "1384 East State Road 92",
    locationCity: "Lehi",
    locationState: "Utah",
    locationZip: "84043"
  },
  {
    locationName: "Kneaders of Logan",
    contactFirst: "Tyson",
    contactLast: "Booth",
    contactPhone: "(509) 868-6657",
    contactEmail: "tyson@kneaders.com",
    locationAddress: "1675 North Main Street",
    locationCity: "Logan",
    locationState: "Utah",
    locationZip: "84341"
  },
  {
    locationName: "Kneaders of Lone Tree",
    contactFirst: "Jill",
    contactLast: "Whitehead",
    contactPhone: "(303) 643-5941",
    contactEmail: "lonetree@kneaders.com",
    locationAddress: "9846 Zenith Meridian Dr",
    locationCity: "Englewood",
    locationState: "Colorado",
    locationZip: "80112"
  },
  {
    locationName: "Kneaders of Mesa McDowell",
    contactFirst: "Jay",
    contactLast: "Rodriguez",
    contactPhone: "(801) 634-5988",
    contactEmail: "tieg@kneaders.com",
    locationAddress: "6611 E McDowell Road",
    locationCity: "Mesa",
    locationState: "Arizona",
    locationZip: "85215"
  },
  {
    locationName: "Kneaders of Mesa Signal Butte",
    contactFirst: "Dustin",
    contactLast: "Jones",
    contactPhone: "(435) 256-5311",
    contactEmail: "dustin@kneaders.com",
    locationAddress: "1142 S Signal Butte Rd",
    locationCity: "Mesa",
    locationState: "Arizona",
    locationZip: "85208"
  },
  {
    locationName: "Kneaders of Northgate",
    contactFirst: "Trista",
    contactLast: "Aamodt",
    contactPhone: "(315) 681-8771",
    contactEmail: "trista@kneaders.com",
    locationAddress: "13482 Bass Pro Drive",
    locationCity: "Colorado Springs",
    locationState: "Colorado",
    locationZip: "80921"
  },
  {
    locationName: "Kneaders of Ogden",
    contactFirst: "Aaron & Rachel",
    contactLast: "Seitzinger",
    contactPhone: "(385) 204-2870",
    contactEmail: "aaron@kneaders.com",
    locationAddress: "1953 Washington Blvd",
    locationCity: "Ogden",
    locationState: "Utah",
    locationZip: "84401"
  },
  {
    locationName: "Kneaders of Oro Valley",
    contactFirst: "Gustave ",
    contactLast: "Johansson",
    contactPhone: "(385) 268-9263",
    contactEmail: "gustave@kneaders.com",
    locationAddress: "9660 North Oracle Road",
    locationCity: "Oro Valley",
    locationState: "Arizona",
    locationZip: "85737"
  },
  {
    locationName: "Kneaders of Overland Park",
    contactFirst: "N/A",
    contactLast: "N/A",
    contactPhone: "",
    contactEmail: "",
    locationAddress: "12180 Blue Valley Parkway",
    locationCity: "Overland Park",
    locationState: "Kansas",
    locationZip: "66213"
  },
  {
    locationName: "Kneaders of Park City",
    contactFirst: "Kaydon",
    contactLast: "Duvall",
    contactPhone: "(801) 367-3653",
    contactEmail: "newpark@fourfoodsgroup.com",
    locationAddress: "1476 West Newpark Blvd",
    locationCity: "Park City",
    locationState: "Utah",
    locationZip: "84098"
  },
  {
    locationName: "Kneaders of Parker",
    contactFirst: "Brady",
    contactLast: "Morlock",
    contactPhone: "(801) 635-6127",
    contactEmail: "parker@kneaders.com",
    locationAddress: "19190 East Main Street",
    locationCity: "Parker",
    locationState: "Colorado",
    locationZip: "80134"
  },
  {
    locationName: "Kneaders of Phoenix Bell",
    contactFirst: "Geno",
    contactLast: "Tuala",
    contactPhone: "(480) 316-8305",
    contactEmail: "eugene@kneaders.com",
    locationAddress: "1150 E Bell Road",
    locationCity: "Phoenix",
    locationState: "Arizona",
    locationZip: "85022"
  },
  {
    locationName: "Kneaders of Queen Creek",
    contactFirst: "Kristen",
    contactLast: "Culver",
    contactPhone: "(480) 481-2211",
    contactEmail: "queencreek@kneaders.com",
    locationAddress: "21157 E Rittenhouse Rd",
    locationCity: "Queen Creek",
    locationState: "Arizona",
    locationZip: "85142"
  },
  {
    locationName: "Kneaders of Saratoga Springs",
    contactFirst: "Nate ",
    contactLast: "Duvall",
    contactPhone: "(801) 380-6346",
    contactEmail: "slove@kneaders.com",
    locationAddress: "1484 Redwood Rd",
    locationCity: "Saratoga Springs",
    locationState: "Utah",
    locationZip: "84045"
  },
  {
    locationName: "Kneaders of Scottsdale",
    contactFirst: "Keith",
    contactLast: "Parry",
    contactPhone: "(480) 355-0740",
    contactEmail: "scot@kneaders.com",
    locationAddress: "15505 N Hayden Road",
    locationCity: "Scottsdale",
    locationState: "Arizona",
    locationZip: "85260"
  },
  {
    locationName: "Kneaders of Serenity Ridge",
    contactFirst: "Kneaders",
    contactLast: "of Serenity Ridge",
    contactPhone: "",
    contactEmail: "",
    locationAddress: "25771 East Smoky Hill Rd",
    locationCity: "Aurora",
    locationState: "Colorado",
    locationZip: "80016"
  },
  {
    locationName: "Kneaders of Spanish Fork",
    contactFirst: "Ryan",
    contactLast: "Duvall",
    contactPhone: "(801) 361-8090",
    contactEmail: "ryan@kneaders.com",
    locationAddress: "531 East 1000 North",
    locationCity: "Spanish Fork",
    locationState: "Utah",
    locationZip: "84660"
  },
  {
    locationName: "Kneaders of St. George",
    contactFirst: "Lowell",
    contactLast: "Hansen",
    contactPhone: "(801) 598-4193",
    contactEmail: "lowell@kneaders.com",
    locationAddress: "199 North Bluff Street",
    locationCity: "St. George",
    locationState: "Utah",
    locationZip: "84771"
  },
  {
    locationName: "Kneaders of St. George II",
    contactFirst: "Kathy",
    contactLast: "Hansen",
    contactPhone: "(801) 860-8606",
    contactEmail: "Kathy@kneaders.com",
    locationAddress: "529 S Mall Drive",
    locationCity: "St. George",
    locationState: "UT",
    locationZip: "84790"
  },
  {
    locationName: "Kneaders of Surprise",
    contactFirst: "Stephen",
    contactLast: "Miller",
    contactPhone: "(602) 423-7596",
    contactEmail: "surprise@kneaders.com",
    locationAddress: "14183 W Bell Rd",
    locationCity: "Surprise",
    locationState: "Arizona",
    locationZip: "85374"
  },
  {
    locationName: "Kneaders of Tempe",
    contactFirst: "Steven",
    contactLast: "Fulilangi",
    contactPhone: "(385) 319-4976",
    contactEmail: "steven@kneaders.com",
    locationAddress: "2030 E Elliot Road",
    locationCity: "Tempe",
    locationState: "Arizona",
    locationZip: "85283"
  },
  {
    locationName: "Kneaders of Thornton",
    contactFirst: "Jill",
    contactLast: "Whitehead",
    contactPhone: "(720) 628-7026",
    contactEmail: "thornton@kneaders.com",
    locationAddress: "9785 Washington Street",
    locationCity: "Thornton",
    locationState: "Colorado",
    locationZip: "80229"
  },
  {
    locationName: "Kneaders of Tucson Broadway",
    contactFirst: "Farani",
    contactLast: "Tua",
    contactPhone: "(801) 410-3161",
    contactEmail: "farani@kneaders.com",
    locationAddress: "135 South Wilmot Road",
    locationCity: "Tucson",
    locationState: "Arizona",
    locationZip: "85711"
  },
  {
    locationName: "Kneaders of Tucson Craycroft",
    contactFirst: "Chase",
    contactLast: "Clark",
    contactPhone: "(520) 273-5370",
    contactEmail: "chase@kneaders.com",
    locationAddress: "3570 N Craycroft",
    locationCity: "Tucson",
    locationState: "Arizona",
    locationZip: "85750"
  },
  {
    locationName: "Kneaders of West Valley",
    contactFirst: "Ezra",
    contactLast: "YoungYen",
    contactPhone: "(801) 719-8404",
    contactEmail: "ezra@kneaders.com",
    locationAddress: "2624 S High Commons Way",
    locationCity: "West Valley",
    locationState: "Utah",
    locationZip: "84120"
  },
  {
    locationName: "Kneaders of Wichita",
    contactFirst: "Michael",
    contactLast: "DeRosia",
    contactPhone: "(801) 921-9708",
    contactEmail: "mderosia@fourfoodsgroup.com",
    locationAddress: "1821 N Rock Road",
    locationCity: "Wichita",
    locationState: "KS",
    locationZip: "67206"
  },
  {
    locationName: "Mo' Bettahs of Bountiful",
    contactFirst: "Tylar",
    contactLast: "Glenn",
    contactPhone: "(702) 767-1675",
    contactEmail: "tylar@mobettahsteaks.com",
    locationAddress: "273 W 500 S",
    locationCity: "Bountiful",
    locationState: "Utah",
    locationZip: "84010"
  },
  {
    locationName: "Mo' Bettahs of Lehi",
    contactFirst: "Shenamarie",
    contactLast: "Alameida-Bornt",
    contactPhone: "(808) 785-8111",
    contactEmail: "shenamarie@mobettahsteaks.com",
    locationAddress: "2975 Club House Drive",
    locationCity: "Lehi",
    locationState: "Utah",
    locationZip: "84043"
  },
  {
    locationName: "Mo' Bettahs of Logan",
    contactFirst: "Kaleo",
    contactLast: "Dipko",
    contactPhone: "(801) 503-7222",
    contactEmail: "kaleo@mobettahsteaks.com",
    locationAddress: "2095 North Main Street ",
    locationCity: "Logan",
    locationState: "Utah",
    locationZip: "84341"
  },
  {
    locationName: "Mo' Bettahs of Midvale",
    contactFirst: "Joseph (JJ) ",
    contactLast: "Johnson",
    contactPhone: "(801) 879-5404",
    contactEmail: "jj@mobettahsteaks.com",
    locationAddress: "7101 S Bingham Junction Blvd.",
    locationCity: "Midvale",
    locationState: "Utah",
    locationZip: "84047"
  },
  {
    locationName: "Mo' Bettahs of Ogden",
    contactFirst: "Tristan",
    contactLast: "Naylor",
    contactPhone: "(435) 994-4448",
    contactEmail: "tristan@mobettahsteaks.com",
    locationAddress: "1102 South Washington Blvd",
    locationCity: "Ogden",
    locationState: "UT",
    locationZip: "84404"
  },
  {
    locationName: "Mo' Bettahs of Orem",
    contactFirst: "Koa",
    contactLast: "Mack",
    contactPhone: "(801) 803-3579",
    contactEmail: "orem@mobettahs.com",
    locationAddress: "1385 S State Street",
    locationCity: "Orem",
    locationState: "Utah",
    locationZip: "84097"
  },
  {
    locationName: "Mo' Bettahs of Pleasant Grove",
    contactFirst: "Corbin",
    contactLast: "Crabtree",
    contactPhone: "",
    contactEmail: "",
    locationAddress: "855 W State Street ",
    locationCity: "Pleasant Grove ",
    locationState: "Utah",
    locationZip: "84062"
  },
  {
    locationName: "Mo' Bettahs of Salt Lake",
    contactFirst: "Tionna",
    contactLast: "Nogales",
    contactPhone: "(801) 755-6889",
    contactEmail: "tionna@mobettahsteaks.com",
    locationAddress: "335 West 1830 South",
    locationCity: "Salt Lake City",
    locationState: "Utah",
    locationZip: "84115"
  },
  {
    locationName: "Mo' Bettahs of South Jordan ",
    contactFirst: "Christy",
    contactLast: "Taufaasau",
    contactPhone: "(808) 238-6367",
    contactEmail: "christy@mobettahsteaks.com",
    locationAddress: "3591 W 11400 S ",
    locationCity: "South Jordan",
    locationState: "Utah",
    locationZip: "84095"
  },
  {
    locationName: "Mo' Bettahs of West Valley",
    contactFirst: "Tionna",
    contactLast: "Nogales",
    contactPhone: "(801) 755-6889",
    contactEmail: "westvalley@mobettahsteaks.com",
    locationAddress: "2731 South 5600 West ",
    locationCity: "West Valley City",
    locationState: "Utah",
    locationZip: "84102"
  },
  {
    locationName: "R&R BBQ of Farmington",
    contactFirst: "Stephen",
    contactLast: "Fairbanks",
    contactPhone: "(435) 631-2354",
    contactEmail: "sfairbanks@randrbbq.com",
    locationAddress: "426 North Cabela’s Drive ",
    locationCity: "Farmington",
    locationState: "Utah",
    locationZip: "84025"
  },
  {
    locationName: "R&R BBQ of Lehi",
    contactFirst: "Chris",
    contactLast: "Baun",
    contactPhone: "(801) 885-5169",
    contactEmail: "cbaun@randrbbq.com",
    locationAddress: "1628 W Traverse Pkwy",
    locationCity: "Lehi",
    locationState: "Utah",
    locationZip: "84043"
  },
  {
    locationName: "R&R BBQ of North Salt Lake",
    contactFirst: "Sheldon",
    contactLast: "Barker",
    contactPhone: "",
    contactEmail: "",
    locationAddress: "Highway 89 & 2600 South",
    locationCity: "North Salt Lake",
    locationState: "UT",
    locationZip: "84054"
  },
  {
    locationName: "R&R BBQ of Pleasant Grove",
    contactFirst: "Jeff",
    contactLast: "Miller",
    contactPhone: "(818) 321-4278",
    contactEmail: "jmiller@randrbbq.com",
    locationAddress: "1977 W Pleasant Grove Blvd",
    locationCity: "Pleasant Grove",
    locationState: "UT",
    locationZip: "84062"
  },
  {
    locationName: "R&R BBQ of Provo",
    contactFirst: "James",
    contactLast: "Larsen",
    contactPhone: "(253) 678-1013",
    contactEmail: "",
    locationAddress: "4801 N University Ave ",
    locationCity: "Provo",
    locationState: "UT ",
    locationZip: "84604"
  },
  {
    locationName: "R&R BBQ of Salt Lake ",
    contactFirst: "MIke ",
    contactLast: "Rode",
    contactPhone: "(385) 285-5805",
    contactEmail: "mrode@randrbbq.com",
    locationAddress: "307 W 600 S",
    locationCity: "Salt Lake City",
    locationState: "Utah",
    locationZip: "84101"
  },
  {
    locationName: "R&R BBQ of South Jordan ",
    contactFirst: "Austin ",
    contactLast: "Wagstaff",
    contactPhone: "(801) 918-3855",
    contactEmail: "austin@randrbbq.com",
    locationAddress: "10646 S 300 W",
    locationCity: "South Jordan",
    locationState: "Utah",
    locationZip: "84095"
  },
  {
    locationName: "R&R Catering Center of Salt Lake",
    contactFirst: "Chad",
    contactLast: "Branagan",
    contactPhone: "(801) 702-3018",
    contactEmail: "chad@randrbbq.com",
    locationAddress: "169 Burton Avenue ",
    locationCity: "Salt Lake City",
    locationState: "UT",
    locationZip: "84101"
  },
  {
    locationName: "Soda Shop of Brown",
    contactFirst: "Chase",
    contactLast: "Wardrop",
    contactPhone: "(480) 794-1054",
    contactEmail: "wardrop@thesodashop.com",
    locationAddress: "2010 East Brown Rd.",
    locationCity: "Mesa",
    locationState: "Arizona",
    locationZip: "85213"
  },
  {
    locationName: "Soda Shop of Greenfield",
    contactFirst: "Dylan ",
    contactLast: "Roeder",
    contactPhone: "(480) 794-1094",
    contactEmail: "roeder@thesodashop.com",
    locationAddress: "4311 East Baseline Rd.",
    locationCity: "Gilbert",
    locationState: "Arizona",
    locationZip: "85234"
  },

  {
    locationName: "Swig of Boulevard",
    contactFirst: "Lexi",
    contactLast: "Venuti",
    contactPhone: "(435) 632-5112",
    contactEmail: "sg2@swignsweets.com",
    locationAddress: "287 W St. George Blvd",
    locationCity: "St. George",
    locationState: "Utah",
    locationZip: "84770"
  },
  {
    locationName: "Swig of Bountiful",
    contactFirst: "Cymbre",
    contactLast: "Flanagan",
    contactPhone: "(713) 459-3864",
    contactEmail: "btfl@swignsweets.com",
    locationAddress: "165 S 500 W",
    locationCity: "Bountiful",
    locationState: "Utah",
    locationZip: "84010"
  },
  {
    locationName: "Swig of Clearfield",
    contactFirst: "Nikole",
    contactLast: "Dyer",
    contactPhone: "(385) 393-0140",
    contactEmail: "clinton@swignsweets.com",
    locationAddress: "916 W 1700 S",
    locationCity: "Clearfield ",
    locationState: "Utah",
    locationZip: "84015"
  },
  {
    locationName: "Swig of Clinton",
    contactFirst: "Nikole ",
    contactLast: "Dyer",
    contactPhone: "(385) 393-0140",
    contactEmail: "clinton@swignsweets.com",
    locationAddress: "1912 W 1800 N",
    locationCity: "Clinton",
    locationState: "Utah",
    locationZip: "84015"
  },
  {
    locationName: "Swig of Dino",
    contactFirst: "Dana",
    contactLast: "Venuti",
    contactPhone: "(435) 632-2888",
    contactEmail: "",
    locationAddress: "553 S Mall Drive ",
    locationCity: "St. George",
    locationState: "Utah",
    locationZip: "84790"
  },
  {
    locationName: "Swig of Draper",
    contactFirst: "Lauren",
    contactLast: "Collins",
    contactPhone: "(801) 634-1267",
    contactEmail: "draper@swignsweets.com",
    locationAddress: "437 E 12300 S",
    locationCity: "Draper",
    locationState: "UT",
    locationZip: "84020"
  },
  {
    locationName: "Swig of Lehi",
    contactFirst: "Caara",
    contactLast: "Varner",
    contactPhone: "(801) 830-2592",
    contactEmail: "lehi@swignsweets.com",
    locationAddress: "1325 E Main Street",
    locationCity: "Lehi",
    locationState: "Utah",
    locationZip: "84043"
  },
  {
    locationName: "Swig of Logan",
    contactFirst: "Laura",
    contactLast: "Allen",
    contactPhone: "(435) 359-2330",
    contactEmail: "laura@swignsweets.com",
    locationAddress: "880 S Main Street",
    locationCity: "Logan",
    locationState: "Utah",
    locationZip: "84341"
  },
  {
    locationName: "Swig of Murray",
    contactFirst: "Mayan",
    contactLast: "Briem",
    contactPhone: "(801) 414-3751",
    contactEmail: "murray@swignsweets.com",
    locationAddress: "5575 S 900 E",
    locationCity: "Murray",
    locationState: "Utah",
    locationZip: "84117"
  },
  {
    locationName: "Swig of Oquirrh",
    contactFirst: "Bella",
    contactLast: "Archuleta",
    contactPhone: "(385) 237-4001",
    contactEmail: "oquirrh@swignsweets.com",
    locationAddress: "11528 S 4000 W",
    locationCity: "South Jordan",
    locationState: "Utah",
    locationZip: "84009"
  },
  {
    locationName: "Swig of Orem",
    contactFirst: "Madison ",
    contactLast: "Morrill",
    contactPhone: "(801) 941-2391",
    contactEmail: "orem@swignsweets.com",
    locationAddress: "584 W 1600 N",
    locationCity: "Orem",
    locationState: "Utah",
    locationZip: "84057"
  },
  {
    locationName: "Swig of Provo",
    contactFirst: "Emily ",
    contactLast: "Ludlow",
    contactPhone: "(385) 312-1578",
    contactEmail: "provo@swignsweets.com",
    locationAddress: "1523 N. Canyon Road ",
    locationCity: "Provo",
    locationState: "Utah",
    locationZip: "84604"
  },
  {
    locationName: "Swig of Santan",
    contactFirst: "Shannon",
    contactLast: "Montierth",
    contactPhone: "(435) 628-1113",
    contactEmail: "santan@swignsweets.com",
    locationAddress: "2919 S. Market Street",
    locationCity: "Gilbert ",
    locationState: "Arizona",
    locationZip: "85297"
  },
  {
    locationName: "Swig of Tabernacle",
    contactFirst: "Abby",
    contactLast: "Richardson",
    contactPhone: "(435) 669-8035",
    contactEmail: "sg1@swignsweets.com",
    locationAddress: "989 E Tabernacle",
    locationCity: "St. George",
    locationState: "Utah",
    locationZip: "84770"
  },
  {
    locationName: "Swig of Trail Crossing",
    contactFirst: "Elizabeth",
    contactLast: "Hackley",
    contactPhone: "(385) 237-0404",
    contactEmail: "trailcrossing@swignsweets.com",
    locationAddress: "5462 W Daybreak Parkway",
    locationCity: "South Jordan",
    locationState: "Utah",
    locationZip: "84009"
  },
  {
    locationName: "Swig of Traverse",
    contactFirst: "Bronwyn ",
    contactLast: "Varner",
    contactPhone: "(385) 352-3900",
    contactEmail: "traverse@swignsweets.com",
    locationAddress: "1881 W Traverse Parkway",
    locationCity: "Lehi",
    locationState: "Utah",
    locationZip: "84043"
  },
  {
    locationName: "Swig of University Mall",
    contactFirst: "David",
    contactLast: "Cisneros",
    contactPhone: "(435) 359-2329",
    contactEmail: "uplace@swignsweets.com",
    locationAddress: "575 E University Parkway",
    locationCity: "Orem",
    locationState: "Utah",
    locationZip: "84097"
  },
  {
    locationName: "Swig of West Draper",
    contactFirst: "Taylor",
    contactLast: "Richards",
    contactPhone: "(801) 350-1386",
    contactEmail: "wdraper@swignsweets.com",
    locationAddress: "196 West 12300 South",
    locationCity: "Draper",
    locationState: "Utah",
    locationZip: "84020"
  }
];
